name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name:
          - linux-amd64
          - macos-amd64
          - macos-aarch64
          - windows-amd64
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
          - os: macos-latest
            build_flags: --target aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v3
    - run: cargo build --verbose --release ${{ matrix.build_flags }}
    - uses: actions/upload-artifact@v3
      with:
        name: jsonsort-${{ runner.os }}-${{ runner.arch }}
        path: target/release/jsonsort
