name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name:
          - linux-amd64
          - macos-amd64
          - macos-aarch64
          - windows-amd64
        include:
          - name: linux-amd64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - name: windows-amd64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - name: macos-amd64
            os: macos-latest
            target: x86_64-apple-darwin

          - name: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v3
    - run: rustup target add ${{ matrix.target }}
    - run: cargo build --verbose --release --locked --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v3
      with:
        name: jsonsort-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/jsonsort
