name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
        include:
          - { target: aarch64-apple-darwin, os: macos-latest }
          - { target: x86_64-apple-darwin, os: macos-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }

    steps:
      - uses: actions/checkout@v3
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --verbose --release --locked --target ${{ matrix.target }}

      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/upload-artifact@v3
        with:
          name: jsonsort-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/jsonsort
            target/${{ matrix.target }}/release/jsonsort.exe

  prerelease:
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    concurrency:
      group: prerelease
      cancel-in-progress: true

    steps:
      - uses: actions/download-artifact@v3
      - run: |
          ls -lR
          mv -v jsonsort-x86_64-unknown-linux-gnu/jsonsrt jsonsrt-linux-x64
          mv -v jsonsort-aarch64-apple-darwin/jsonsrt jsonsrt-macos-aarch64
          mv -v jsonsort-x86_64-apple-darwin/jsonsrt jsonsrt-macos-x64
          mv -v jsonsort-x86_64-pc-windows-msvc/jsonsrt.exe jsonsrt-windows-x64.exe

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: jsonsrt-head
          prerelease: true
          title: jsonsrt-head
          files: |
            jsonsrt-*
