name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc

        include:
          - name: x86_64-apple-darwin
            os: macos-latest

          - name: aarch64-apple-darwin
            os: macos-latest

          - name: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - name: x86_64-pc-windows-msvc
            os: windows-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup target add ${{ matrix.target }}
    - run: cargo build --verbose --release --locked --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v3
      with:
        name: jsonsort-${{ matrix.target }}.zip
        path: |
          target/${{ matrix.target }}/release/jsonsort
          target/${{ matrix.target }}/release/jsonsort.exe
